<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" total="11" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="27378" started-at="2015-12-24T09:06:02Z" finished-at="2015-12-24T09:06:29Z">
    <groups>
    </groups>
    <test name="Login" duration-ms="22888" started-at="2015-12-24T09:06:02Z" finished-at="2015-12-24T09:06:25Z">
      <class name="com.vsii.tsc.guru.testcase.Login">
        <test-method status="PASS" signature="setupClass()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="setupClass" is-config="true" duration-ms="31" started-at="2015-12-24T16:06:02Z" finished-at="2015-12-24T16:06:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupClass -->
        <test-method status="PASS" signature="LO01()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO01" duration-ms="116" started-at="2015-12-24T16:06:02Z" description="Verify Title of Login Page" finished-at="2015-12-24T16:06:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO01 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="2323" started-at="2015-12-24T16:06:02Z" finished-at="2015-12-24T16:06:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="LO02(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO02" duration-ms="1576" started-at="2015-12-24T16:06:05Z" description="verify Login" data-provider="dpLogin" finished-at="2015-12-24T16:06:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Tester01]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nAgezam ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User or Password is not valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="706" started-at="2015-12-24T16:06:06Z" finished-at="2015-12-24T16:06:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="LO02(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO02" duration-ms="1897" started-at="2015-12-24T16:06:07Z" description="verify Login" data-provider="dpLogin" finished-at="2015-12-24T16:06:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr22018]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User or Password is not valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="301" started-at="2015-12-24T16:06:09Z" finished-at="2015-12-24T16:06:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="LO02(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO02" duration-ms="1777" started-at="2015-12-24T16:06:09Z" description="verify Login" data-provider="dpLogin" finished-at="2015-12-24T16:06:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Tester02]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User or Password is not valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="291" started-at="2015-12-24T16:06:11Z" finished-at="2015-12-24T16:06:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="LO02(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO02" duration-ms="1791" started-at="2015-12-24T16:06:11Z" description="verify Login" data-provider="dpLogin" finished-at="2015-12-24T16:06:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[""]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nAgezam ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User-ID must not be blank]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.vsii.tsc.guru.testcase.Login.LO02(Login.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="292" started-at="2015-12-24T16:06:13Z" finished-at="2015-12-24T16:06:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="LO02(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO02" duration-ms="1792" started-at="2015-12-24T16:06:14Z" description="verify Login" data-provider="dpLogin" finished-at="2015-12-24T16:06:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr22018]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[""]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Password must not be blank]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.vsii.tsc.guru.testcase.Login.LO02(Login.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="290" started-at="2015-12-24T16:06:15Z" finished-at="2015-12-24T16:06:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="LO02(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO02" duration-ms="1759" started-at="2015-12-24T16:06:16Z" description="verify Login" data-provider="dpLogin" finished-at="2015-12-24T16:06:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[""]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[""]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User or Password is not valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="305" started-at="2015-12-24T16:06:17Z" finished-at="2015-12-24T16:06:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="LO02(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO02" duration-ms="4488" started-at="2015-12-24T16:06:18Z" description="verify Login" data-provider="dpLogin" finished-at="2015-12-24T16:06:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr22018]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nAgezam ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Manger Id : mngr22018]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO02 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="afterMethod" is-config="true" duration-ms="2404" started-at="2015-12-24T16:06:22Z" finished-at="2015-12-24T16:06:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="LO03(java.lang.String, java.lang.String)[pri:2, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="LO03" duration-ms="0" started-at="2015-12-24T16:06:25Z" description="verify_Reset_Button" finished-at="2015-12-24T16:06:25Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method LO03 requires 2 parameters but 0 were supplied in the @Test annotation.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method LO03 requires 2 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:191)
	at org.testng.internal.Parameters.createParameters(Parameters.java:127)
	at org.testng.internal.Parameters.createParameters(Parameters.java:376)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LO03 -->
        <test-method status="PASS" signature="teardownClass()[pri:0, instance:com.vsii.tsc.guru.testcase.Login@6aaa5eb0]" name="teardownClass" is-config="true" duration-ms="0" started-at="2015-12-24T16:06:25Z" finished-at="2015-12-24T16:06:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownClass -->
      </class> <!-- com.vsii.tsc.guru.testcase.Login -->
    </test> <!-- Login -->
    <test name="NewCustomer" duration-ms="4464" started-at="2015-12-24T09:06:25Z" finished-at="2015-12-24T09:06:29Z">
      <class name="com.vsii.tsc.guru.testcase.NewCustomer">
        <test-method status="PASS" signature="setupClass()[pri:0, instance:com.vsii.tsc.guru.testcase.NewCustomer@90f6bfd]" name="setupClass" is-config="true" duration-ms="34" started-at="2015-12-24T16:06:25Z" finished-at="2015-12-24T16:06:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupClass -->
        <test-method status="PASS" signature="CN01()[pri:0, instance:com.vsii.tsc.guru.testcase.NewCustomer@90f6bfd]" name="CN01" duration-ms="1956" started-at="2015-12-24T16:06:25Z" finished-at="2015-12-24T16:06:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CN01 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.vsii.tsc.guru.testcase.NewCustomer@90f6bfd]" name="afterMethod" is-config="true" duration-ms="2335" started-at="2015-12-24T16:06:27Z" finished-at="2015-12-24T16:06:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="CN02(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.vsii.tsc.guru.testcase.NewCustomer@90f6bfd]" name="CN02" duration-ms="0" started-at="2015-12-24T16:06:29Z" description="Verify Add New Customer" data-provider="dpNewCustomer" finished-at="2015-12-24T16:06:29Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:162)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
Caused by: java.lang.NullPointerException
	at com.vsii.tsc.guru.utility.Utility.getTable(Utility.java:101)
	at com.vsii.tsc.guru.data.TestData.getCustomerData(TestData.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:136)
	... 20 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CN02 -->
      </class> <!-- com.vsii.tsc.guru.testcase.NewCustomer -->
      <class name="com.vsii.tsc.guru.testbase.TestBase">
        <test-method status="PASS" signature="setupSuite()[pri:0, instance:com.vsii.tsc.guru.testbase.TestBase@47f6473]" name="setupSuite" is-config="true" duration-ms="8442" started-at="2015-12-24T16:05:53Z" finished-at="2015-12-24T16:06:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method status="PASS" signature="teardownSuite()[pri:0, instance:com.vsii.tsc.guru.testbase.TestBase@47f6473]" name="teardownSuite" is-config="true" duration-ms="0" started-at="2015-12-24T16:06:29Z" finished-at="2015-12-24T16:06:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownSuite -->
      </class> <!-- com.vsii.tsc.guru.testbase.TestBase -->
    </test> <!-- NewCustomer -->
  </suite> <!-- Suite -->
</testng-results>
